# This is a basic workflow to help you get started with Actions

name: Stage the app

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
      - name: Run hello
        run: echo "Hello"
